triggers:
  - github:
      version: 2
      useInitiator: false
      entryPoint: onPush
      useEventCommitId: true
      conditions:
        type: push
        branch: "main"
flows:
  onPush:
    - log: "OK"
    - log: "OK2"

