triggers:
  - github:
      version: 2
      useInitiator: false
      entryPoint: onPush
      useEventCommitId: true
      conditions:
        type: push
        branch: "main"
        sender: "^(?!.*(jenkinspan|SVC-Looper|SVCassortmentbuild)).*$"
      exclusive:
        group: masterPush-deploy
        mode: wait

flows:
  onPush:
    - log: "OK"
    - log: "OK2"

