triggers:
  - github:
      version: 2
      useInitiator: false
      entryPoint: onPush
      useEventCommitId: true
      conditions:
        type: "pull_request"
        status: "opened"
        branch: ".*"
flows:
  onPush:
    - log: "OK"
    - log: "OK2"

